### ISSUE TITLE
Archival imminent

### ISSUE THREAD

**Issue by abhinav** [abhinav/gitprompt#13]
I've switched to starship prompt and no longer need this tool.
The following configuration snippets for starship create a similar git prompt:

```toml
[git_branch]
format = '\([$branch(:$remote_branch)]($style)'
symbol = ""
style = "bold purple"

[git_commit]
format = '\([$hash]($style)$tag'

[git_status]
format = '($ahead_behind)(|[$staged$conflicted](red)[$deleted$renamed$modified](blue)$untracked)\) '
staged = "●${count}"
conflicted = "=${count}"
deleted = "✘${count}"
renamed = "»${count}"
modified = "✚${count}"
untracked = "…"
ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
style = ""
```
